### ISSUE TITLE
Add concurrency checks to most workflows (if new workflow spawned, cancel old)

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/gh-workflows#65]
Something like this:

```yaml
# Automatically cancel older in-progress jobs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true
```

should cancel the workflow if it's triggered twice on the same branch / PR.

Particularly useful for merging multiple PRs in succession to avoid multiple re-deploys (only the last is redeployed).
